### ISSUE TITLE
error: unknown package in top-level dependencies: jeremy:react-accounts-ui

### ISSUE THREAD

**Issue by joseconstela** [reactioncommerce/launchdock#27]
Fails to build the docker image and/or while building the meteor app

```
=> Errors while initializing project:

While selecting package versions:
error: unknown package in top-level dependencies: jeremy:react-accounts-ui
unknown package in top-level dependencies: jeremy:react-accounts-ui-basic
```

**Comment by jshimko** [comment]
Thanks for taking the time to report the issue @joseconstela.  

So yeah, that's happening because I had custom accounts UI packages for React in my local packages folder that were not published on Atmosphere yet because I hadn't finished writing docs for them.  I just removed one of them and published the remaining one, so that issue should be fixed  now (on the development branch).  The docs for that package still don't exist, but you won't need to read them to be able to use it.  It's already set up in the app.  But feel free to check out [the code](https://github.com/jshimko/react-accounts-ui) if you want to see the source.

Also, Launchdock is under very heavy development right now and will be for the next month or so.  The app and API are changing significantly every day and the setup docs are not up to date with how to get things running with Rancher (which is also changing right now).  So... unless you're planning on doing somewhat advanced development work, you may want to wait a few weeks before attempting to use the project.  It most certainly won't be an easy setup unless you already know how to configure Rancher and Launchdock to communicate.  However, most of my efforts over the next week or so are aimed specifically at making that initial setup easier and less manual.  

Launchdock is also currently hard coded to launch a 4 container Meteor stack (1 app container + 3 container Mongo replica set), but there are big changes coming for the stack template options as well.

All of that said, if you're comfortable getting under the hood and would like to contribute, please feel free to get in touch.  We're always happy to have more help on the project if you're comfortable with Meteor, Docker, Rancher, etc.  Otherwise, it's probably best to wait a few more weeks for things to settle down and get a little easier to use.

This issue should be fixed now, so I'm going to close it.  Thanks again for reporting it!

**Comment by joseconstela** [comment]
Thanks to you @jshimko !
